### PR TITLE
Upgrade Ruby.

### PR DESCRIPTION
**Pull request by bigxiang**
https://lovewithfood.atlassian.net/browse/EI-381

### CODE REVIEW

**Comment by bigxiang** [comment]
@htanata Could you review it? Thanks.

**Comment by htanata** [comment]
For the next pull request, it's better if you create a subtask for each so it's easier to keep track of.

**Comment by htanata** [comment]
Looks good. Can you improve the commit message to "Upgrade Ruby to 2.4.2." The commit message should be as clear as possible.

**Comment by bigxiang** [comment]
@htanata Code updated, please have another look, thanks.

**Pull request merged**
